# ==========================================
# HYDRAVISION CLOUD DATABASE (AIVEN) - LOCAL TESTING
# ==========================================
# We added explicit SSL negotiation parameters to the URL
spring.datasource.url=jdbc:mysql://hydravision-db-yadlashivaramaraju-9121.i.aivencloud.com:20370/defaultdb?sslMode=REQUIRED&useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Explicitly tell Hibernate we are using MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB